---
# defaults file for dcos-cli
dcos_cli_image: capgemini/dcos-cli
dcos_cli_zk_master_peers: "zk://{{ zookeeper_peers_nodes }}/mesos"
dcos_cli_mesos_master_url: "http://{{ ansible_ssh_host }}:5050"
dcos_cli_marathon_url: "http://{{ ansible_ssh_host }}:8080"
dcos_cli_sources: '["https://github.com/Capgemini/universe/archive/version-1.x.zip",]'
dcos_cli_frameworks_list:
  - cassandra
  - chronos
  - exhibitor
# Type flag allows you to set up a command which you want to use to run an app.
# To run one app use "type: app" and to run group of apps use "type: group".
dcos_cli_apps_list:
  - { name: prometheus, type: app }
  - { name: promdash, type: group }

# apps
prometheus_image: prom/prometheus
prometheus_image_tag: 0.16.1
