---
# tasks file for consul
- name: remove consul override
  file: path=/etc/init/consul.override state=absent

- name: start consul
  service: name=consul state=started

- name: configure consul
  sudo: yes
  template: src=consul.json.j2 dest=/etc/consul.d/consul.json owner=root group=root mode=0644
  notify:
    - Restart consul
  tags:
    - consul

- name: configure atlas for consul
  sudo: yes
  template: src=atlas.json.j2 dest=/etc/consul.d/atlas.json owner=root group=root mode=0644
  when: consul_atlas_join
  notify:
    - Restart consul
  tags:
    - consul

- name: remove consul-join override
  file: path=/etc/init/consul-join.override state=absent
  when: consul_join is defined

- name: configure consul-join
  sudo: yes
  template: src=consul-join.j2 dest=/etc/service/consul-join owner=root group=root mode=0644
  notify:
    - Restart consul
  when: consul_join is defined
  tags:
    - consul
