- include_vars: "{{ item }}.yml"
  with_items: "{{ dcos_cli_frameworks_list }}"

- name: create config directory
  when: "dcos_cli_framework_{{ item }}_enabled | bool"
  run_once: true
  template:
    src: "{{ item }}-config.j2"
    dest: "/tmp/{{ item }}-config"
    mode: 0755
  become: yes
  tags:
    - "{{ item }}"
  with_items:
    - "{{ dcos_cli_frameworks_list }}"

- name: install dcos-cli package
  when: "dcos_cli_framework_{{ item }}_enabled | bool"
  run_once: true
  docker:
    name: "{{ item }}"
    image: "{{ dcos_cli_image }}"
    state: started
    command: "package install --options=/config --yes {{ item }}"
    volumes:
    - "/tmp/{{ item }}-config:/config"
    env:
      MESOS_MASTER_URL: "{{ dcos_cli_mesos_master_url }}"
      MARATHON_URL: "{{ dcos_cli_marathon_url }}"
      SOURCES: "{{ dcos_cli_sources }}"
  tags:
    - "{{ item }}"
  with_items:
    - "{{ dcos_cli_frameworks_list }}"

- name: uninstall dcos-cli package
  when: "not dcos_cli_framework_{{ item }}_enabled | bool"
  run_once: true
  docker:
    name: "{{ item }}"
    image: "{{ dcos_cli_image }}"
    state: started
    command: "package uninstall {{ item }}"
    env:
      MESOS_MASTER_URL: "{{ dcos_cli_mesos_master_url }}"
      MARATHON_URL: "{{ dcos_cli_marathon_url }}"
  tags:
    - "{{ item }}"
  with_items:
    - "{{ dcos_cli_frameworks_list }}"
