---
# defaults file for zookeeper
zookeeper_client_port: 2181
zookeeper_leader_connect_port: 2888
zookeeper_leader_election_port: 3888
zookeeper_server_group: zookeeper_servers
zookeeper_id: "
    {%- for host in groups[zookeeper_server_group] -%}
      {%- if host == 'default' or host == inventory_hostname or host == ansible_fqdn or host in ansible_all_ipv4_addresses -%}
        {{ loop.index }}
      {%- endif -%}
    {%- endfor -%}
"
