---
# defaults file for haproxy
haproxy_image: asteris/haproxy-consul
haproxy_image_tag: latest

# Set the domain that haproxy uses to match URLs to internal apps.
# For example, if all your apps will be
#    app1.example.com, app2.example.com, etc.  set this to 'example.com'
haproxy_domain: example.com

haproxy_rebuild_container: False

consul_template_dir: /mnt/consul-template.d
consul_template_loglevel: debug
consul_backend: consul.service.consul:8500
consul_template_version: 0.12.2
