---
# Tasks for Agent nodes
- name: create mesos-agent work directory
  file:
    path: "{{ mesos_agent_work_dir }}"
    state: directory
    mode: 0755
  become: yes
  tags:
    - mesos-agent

- name: detect gpu support
  become: yes
  command: ls -al | grep -i "nvidia"
  args:
    chdir: /dev
  register: nvidio_drivers
  tags:
    - mesos-agent

- name: add gpu support for slave
  set_fact:
    mesos_gpu: true
  when: nvidio_drivers.stdout contains "nvidia0"
  tags:
    - mesos-agent

- name: deploy mesos-agent service
  become: yes
  become_user: root
  template:
    src: mesos-agent.service.j2
    dest: /etc/systemd/system/mesos-agent.service
  notify:
    - reload systemd
    - restart mesos agent
  tags:
    - mesos-agent

- name: ensure mesos-agent is running (and enable it at boot)
  become: yes
  service:
    name: mesos-agent
    state: started
    enabled: yes
  tags:
    - mesos-agent

- name: run prometheus mesos agent exporter container
  when: prometheus_enabled|bool
  docker:
    name: mesos-exporter
    image: "{{ prometheus_mesos_exporter_image }}"
    command: "-exporter.scrape-mode=agent -exporter.url=http://{{ mesos_hostname }}:{{ mesos_agent_port }}"
    state: started
    restart_policy: always
    ports:
    - "{{ prometheus_mesos_exporter_port }}:{{ prometheus_mesos_exporter_port }}"
  environment: "{{ proxy_env }}"
  tags:
    - prometheus
    - mesos_agent

- name: Set mesos-exporter consul service definition
  when: prometheus_enabled|bool
  become: yes
  template:
    src: mesos-exporter-consul.j2
    dest: "{{ consul_dir }}/mesos-exporter.json"
  notify:
    - restart consul
  tags:
    - prometheus
    - mesos_agent
