---
# Common
consul_dir: /etc/consul.d
mesos_executor_registration_timeout: 10mins
mesos_cluster_name: "Cluster01"
mesos_ip: "{{ ansible_default_ipv4.address }}"
mesos_hostname: "{{ ansible_ssh_host }}"
mesos_docker_socket: "/var/run/weave/weave.sock"
mesos_version: "0.27.1-2.0.226.ubuntu1404"

# Defaults file for mesos-salve
mesos_slave_port: 5051
mesos_containerizers: "docker,mesos"
mesos_resources: "ports(*):[31000-32000]"
mesos_slave_work_dir: "/tmp/mesos"
mesos_slave_image: "mesosphere/mesos-slave:{{ mesos_version }}"

# Defaults file for mesos-master
mesos_zookeeper_group: zookeeper_servers
mesos_master_port: 5050
mesos_master_work_dir: "/var/lib/mesos"
mesos_master_image: "mesosphere/mesos-master:{{ mesos_version }}"
mesos_master_command: "--registry=replicated_log"

prometheus_mesos_exporter_image: "prom/mesos-exporter:latest"
prometheus_mesos_exporter_port: 9105
prometheus_mesos_exporter_consul_service_id: "{{ ansible_hostname }}:mesos-exporter:{{ prometheus_mesos_exporter_port }}"

# The Mesos quorum value is based on the number of Mesos Masters. Take the
# number of masters, divide by 2, and round-up to nearest integer. For example,
# if there are 1 or 2 masters the quorum count is 1. If there are 3 or 4
# masters then the quorum count is 2. For 5 or 6 masters it's 3 and so on.
mesos_quorum: "
{% if mesos_master_quorum is defined %}
{{ mesos_master_quorum }}
{% else %}
{{ ( groups.mesos_masters|count / 2) | round(0, 'ceil') | int }}
{%- endif -%}
"
