---
# defaults file for consul
consul_is_server: yes
consul_dc: dc1
consul_servers_group: consul_servers
consul_advertise: "{{ ansible_default_ipv4.address }}"
consul_bind_addr: "{{ ansible_default_ipv4.address }}"
consul_bootstrap_expect: "{{ groups[consul_servers_group] | length }}"
consul_client_addr: "0.0.0.0"
consul_atlas_join: false
