---
# tasks file for weave
- name: include all interfaces.d
  sudo: yes
  lineinfile:
    dest: /etc/network/interfaces
    state: present
    line: 'source /etc/network/interfaces.d/*.cfg'
  tags:
    - weave

# Start docker as it is a requirement for weave create-bridge.
- name: Start up docker
  service:
    name: docker
    state: started
  tags:
    - weave

- name: configure weave interface
  sudo: yes
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces.d/weave.cfg
    owner: root
    group: root
    mode: 0644
  tags:
    - weave

# Create weave bridge.
- name: bring up weave bridge
  command: ifup weave
  sudo: yes

- name: weave login vault
  sudo: yes
  shell: "{{ weave_command_login_vault }}"
  register: vault_login_output
  tags:
    - vault

- name: weave set vault token
  run_once: true
  sudo: yes
  set_fact:
    tmp_client_token: "{{ (vault_login_output.stdout | from_json)['auth']['client_token'] }}"
  tags:
    - vault

- name: upload weave template service
  template:
    src: weave.conf.j2
    dest: "/etc/init/weave.conf"
    mode: 0755
  sudo: yes
  tags:
    - weave

# Restart docker with weave bridge available and triggers weave service.
- name: configure weave bridge for docker
  sudo: yes
  lineinfile:
    dest: /etc/default/docker
    state: present
    regexp: ^DOCKER_OPTS=.*--bridge=weave.*
    line: 'DOCKER_OPTS=\"$DOCKER_OPTS {{ weave_docker_opts }}\"'
  notify:
    - restart docker
  tags:
    - weave

- name: download weave scope
  get_url:
    url: "{{ weave_scope_url }}"
    dest: "{{ weave_scope_dest }}"
    mode: 0755
    validate_certs: no
  environment: proxy_env
  tags:
    - weave

- name: upload weave scope template service
  template:
    src: scope.conf.j2
    dest: "/etc/init/weavescope.conf"
    mode: 0755
  sudo: yes
  tags:
    - weave
