---
# tasks file for dnsmasq
- name: create dnsmasq config directory
  file:
    path: "/etc/dnsmasq.d"
    state: directory
    mode: 0755
  sudo: yes
  tags:
    - dnsmasq

- name: configure consul resolution dnsmasq
  sudo: yes
  template:
    src: 10-consul.j2
    dest: /etc/dnsmasq.d/10-consul
    owner: root
    group: root
    mode: 0644
  notify:
    - restart dnsmasq
  tags:
    - dnsmasq

- name: destroy old dnsmasq container
  when: dnsmasq_rebuild_container
  docker:
    name: dnsmasq
    image: "{{ dnsmasq_image }}"
    state: absent
  tags:
    - dnsmasq

# This should be using -cap-add=NET_ADMIN rather than privileged: true.
# This will be supported in Ansible 2.0
- name: run dnsmasq container
  docker:
    name: dnsmasq
    image: "{{ dnsmasq_image }}"
    state: started
    net: "host"
    privileged: true
    volumes:
    - "{{ dnsmasq_config_folder }}/:{{ dnsmasq_config_folder }}/"
    ports:
    - "53:53/tcp"
    - "53:53/udp"
    command: "-r {{ dnsmasq_resolvconf_file }} --conf-dir={{ dnsmasq_config_folder }}"

- name: upload dnsmasq template service
  template:
    src: dnsmasq.conf.j2
    dest: /etc/init/dnsmasq.conf
    mode: 0755
  sudo: yes
  tags:
    - dnsmasq

- name: ensure dnsmasq is running (and enable it at boot)
  service:
    name: dnsmasq
    state: started
    enabled: yes
  tags:
    - dnsmasq
