- name: reload systemd
  become: yes
  command: systemctl daemon-reload

- name: restart consul
  service:
    name: consul
    state: restarted
  become: yes
  notify:
    - wait for consul to listen

- name: wait for consul to listen
  wait_for:
    port: 8500

- name: restart docker
  service:
   name: docker
   state: restarted
  become: yes
  notify:
  - wait for weave to listen

- name: wait for weave to listen
  wait_for:
    port: 6783
    delay: 10
