---
# defaults file for marathon
marathon_consul_dir: /etc/consul.d
marathon_enabled: true
marathon_version: '0.15.2'
marathon_restart_policy: 'always'
marathon_net: 'host'
marathon_hostname: "{{ ansible_ssh_host }}"
marathon_port: '8080'
marathon_container_memory_limit: '512MB'
marathon_java_settings: '-Xmx512m -Xms512m -XX:+HeapDumpOnOutOfMemoryError'
marathon_artifact_store: 'file:///store'
marathon_artifact_store_dir: '/etc/marathon/store'
marathon_server_zk_group: marathon_servers
marathon_image: "mesosphere/marathon:v{{ marathon_version }}"
marathon_master_peers: "zk://{{ zookeeper_peers_nodes }}/mesos"
marathon_zk_peers: "zk://{{ zookeeper_peers_nodes }}/marathon"
marathon_command: "--event_subscriber http_callback --artifact_store {{ marathon_artifact_store }} --hostname {{ marathon_hostname }} --master {{ marathon_master_peers }} --zk {{ marathon_zk_peers }}"
